"use client";

import { useEffect } from "react";
import { truncateMiddle } from "@/components/hero/terminal-data";
import type { MempoolTxRow } from "./mock-data";
import { useTransactionAnalysis } from "./useTransactionAnalysis";
import type { AnalysisFlowNode, AnalysisVerdict } from "./analysis-types";

const RISK_COLOR: Record<"low" | "medium" | "high", string> = {
  low: "#34ffa0",
  medium: "#ffb545",
  high: "#ff4d6a",
};

const VERDICT_STYLE: Record<AnalysisVerdict, { label: string; color: string; bg: string }> = {
  benign: { label: "Benign", color: "text-emerald", bg: "bg-emerald/10 border-emerald/40" },
  suspicious: { label: "Suspicious", color: "text-amber", bg: "bg-amber/10 border-amber/40" },
  "high-risk": { label: "High Risk", color: "text-danger", bg: "bg-danger/10 border-danger/40" },
};

function scoreColor(score: number): string {
  if (score >= 66) return "#ff4d6a";
  if (score >= 33) return "#ffb545";
  return "#34ffa0";
}

function FlowMap({ nodes }: { nodes: AnalysisFlowNode[] }) {
  const positions = [70, 200, 330];
  const y = 46;

  return (
    <svg viewBox="0 0 400 100" className="w-full">
      {positions.slice(0, nodes.length - 1).map((x, i) => (
        <line
          key={`line-${i}`}
          x1={x + 24}
          y1={y}
          x2={positions[i + 1] - 24}
          y2={y}
          stroke="rgba(127,168,149,0.35)"
          strokeWidth={1.5}
          strokeDasharray="3 4"
        />
      ))}
      {nodes.map((node, i) => {
        const cx = positions[i] ?? positions[positions.length - 1];
        const color = RISK_COLOR[node.risk];
        // The model doesn't always follow the "short label" instruction, and
        // has repeated the same id across nodes — key on position, not id,
        // and always truncate so long addresses can't overlap neighbors.
        const label =
          node.label.length > 16 ? truncateMiddle(node.label, 6, 4) : node.label;
        return (
          <g key={`${node.role}-${i}`}>
            <circle cx={cx} cy={y} r={20} fill="rgba(3,5,3,0.9)" stroke={color} strokeWidth={1.75} />
            <circle cx={cx} cy={y} r={3} fill={color} />
            <text
              x={cx}
              y={y + 38}
              textAnchor="middle"
              fill="#dff7e8"
              fontSize="9"
              fontFamily="var(--font-terminal-mono), monospace"
            >
              {node.role}
            </text>
            <text
              x={cx}
              y={y + 50}
              textAnchor="middle"
              fill="#7fa895"
              fontSize="8.5"
              fontFamily="var(--font-terminal-mono), monospace"
            >
              {label}
            </text>
          </g>
        );
      })}
    </svg>
  );
}

export function TransactionAnalysisPanel({
  tx,
  onClose,
}: {
  tx: MempoolTxRow;
  onClose: () => void;
}) {
  const { status, data, error, analyze } = useTransactionAnalysis();

  useEffect(() => {
    analyze(tx);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tx.id]);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [onClose]);

  return (
    <div className="fixed inset-0 z-[60] flex justify-end">
      <button
        type="button"
        aria-label="Close analysis panel"
        onClick={onClose}
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
      />

      <div className="hud-panel animate-hud-in relative flex h-full w-full max-w-md flex-col overflow-y-auto rounded-none border-l p-5 sm:p-6">
        <div className="flex items-start justify-between gap-4">
          <div>
            <p className="font-mono text-[10px] uppercase tracking-[0.3em] text-cyan">
              AI Analysis
            </p>
            <p className="mt-1 font-mono text-xs text-fg-dim">
              {truncateMiddle(tx.hash, 10, 8)}
            </p>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-sm border border-fg-dim/30 px-2.5 py-1.5 font-mono text-xs text-fg-dim transition-colors hover:border-fg-dim/60 hover:text-fg"
          >
            Close
          </button>
        </div>

        <p className="mt-3 font-mono text-[10px] leading-relaxed text-fg-dim/70">
          Generated by AI over simulated mempool data — for demonstration only, not a real
          security finding.
        </p>

        {status === "loading" && (
          <div className="mt-10 flex flex-1 flex-col items-center justify-center gap-3 text-center">
            <span className="h-2 w-2 animate-pulse-dot rounded-full bg-emerald" />
            <p className="font-mono text-xs uppercase tracking-[0.14em] text-fg-dim">
              Analyzing transaction…
            </p>
          </div>
        )}

        {status === "error" && (
          <div className="mt-10 flex flex-1 flex-col items-center justify-center gap-3 text-center">
            <p className="max-w-xs font-mono text-xs text-danger">{error}</p>
            <button
              type="button"
              onClick={() => analyze(tx)}
              className="rounded-sm border border-fg-dim/30 px-4 py-2 font-mono text-[11px] uppercase tracking-[0.1em] text-fg-dim hover:border-fg-dim/60 hover:text-fg"
            >
              Retry
            </button>
          </div>
        )}

        {status === "done" && data && (
          <div className="mt-6 flex flex-col gap-7">
            <div className="flex items-center gap-3">
              <span
                className={`rounded-sm border px-2.5 py-1 font-mono text-[11px] font-semibold uppercase tracking-[0.1em] ${VERDICT_STYLE[data.verdict].bg} ${VERDICT_STYLE[data.verdict].color}`}
              >
                {VERDICT_STYLE[data.verdict].label}
              </span>
              <span className="font-mono text-sm text-fg tabular-nums">
                risk <span style={{ color: scoreColor(data.riskScore) }}>{data.riskScore}</span>
                <span className="text-fg-dim">/100</span>
              </span>
            </div>

            <p className="text-sm leading-relaxed text-fg-dim">{data.summary}</p>

            <div>
              <p className="mb-3 font-mono text-[10px] uppercase tracking-[0.2em] text-fg-dim">
                Analysis Map
              </p>
              <div className="hud-panel rounded-md px-3 py-4">
                <FlowMap nodes={data.flow} />
              </div>
            </div>

            <div>
              <p className="mb-3 font-mono text-[10px] uppercase tracking-[0.2em] text-fg-dim">
                Risk Factors
              </p>
              <div className="flex flex-col gap-3.5">
                {data.factors.map((factor) => (
                  <div key={factor.label}>
                    <div className="flex items-baseline justify-between gap-2">
                      <span className="text-xs text-fg">{factor.label}</span>
                      <span
                        className="font-mono text-[11px] tabular-nums"
                        style={{ color: scoreColor(factor.score) }}
                      >
                        {factor.score}
                      </span>
                    </div>
                    <div className="mt-1.5 h-1 overflow-hidden rounded-full bg-fg-dim/10">
                      <div
                        className="h-full rounded-full transition-[width] duration-700"
                        style={{
                          width: `${Math.min(100, Math.max(0, factor.score))}%`,
                          background: scoreColor(factor.score),
                        }}
                      />
                    </div>
                    <p className="mt-1 font-mono text-[10.5px] text-fg-dim">{factor.note}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
